### ISSUE TITLE
Пробная задача

### ISSUE THREAD

**Issue by VladimirVladimirovich1955** [EDTJasmin/PZ401#1]
Сделать два дела

- [x] 1. Первое дело
- [ ] 2. Второе дело

**Comment by VladimirVladimirovich1955** [comment]
Это - предварительная вводная к началу первого этапа.

**Comment by Vlavianos2021** [comment]
Докладываю: первое дело сделано!

**Comment by VladimirVladimirovich1955** [comment]
Хорошо! 
Когда будет сделано второе, последнее, дело?

**Comment by Vlavianos2021** [comment]
Второе дело тоже сделано. Задача выполнена!

**Comment by VladimirVladimirovich1955** [comment]
Задача будет закрыта сейчас!

**Comment by VladimirVladimirovich1955** [comment]
Закрываю!
